### ISSUE TITLE
Document that 'io.resin.features.dbus' label has to be added

### ISSUE THREAD

**Issue by moritz89** [resin-io-playground/resin-avahi-dbus#1]
In the case of using the image in a multi-docker environment (docker-compose), it is necessary to specify the **dbus label** to expose its interface. Would it make sense to add it in this example? The following docker-compose setup works:

```
version: '2'

services:
  avahi:
    build: ./avahi
    container_name: avahi
    privileged: true
    labels:
      io.resin.features.dbus: '1'
```

The relevant documentation is available on the [multicontainer](https://docs.resin.io/learn/develop/multicontainer/#labels) pages. The directory was reorganized to be a subfolder:

```
root-folder
  - docker-compose.yml
  - avahi
    - Dockerfile.template
    - myserver.py
    - README.md
    - requirements.txt
    - start.sh
    - avahi
      - __init__.py
      - server.py
      - service.py
```
